from __future__ import annotations

from ._enums import (
    AVAILABLE_MODELS,
    FinishReason,
    Model,
    ResponseFormatType,
    Role,
    ThinkingMode,
    ToolChoice,
)
from .client import AsyncKimiClient, KimiClient
from .exceptions import (
    KimiAPIError,
    KimiAuthenticationError,
    KimiBadRequestError,
    KimiError,
    KimiNotFoundError,
    KimiPermissionError,
    KimiRateLimitError,
    KimiServerError,
)
from .types import (
    AssistantMessage,
    BalanceData,
    BalanceInfo,
    ChatCompletion,
    ChatCompletionChunk,
    ChatCompletionRequest,
    Choice,
    ChoiceDelta,
    ContentPart,
    FunctionCall,
    FunctionDef,
    ImageUrl,
    ImageUrlPart,
    JsonSchemaSpec,
    Message,
    ModelInfo,
    ModelList,
    ResponseFormat,
    StreamChoice,
    StreamOptions,
    TextPart,
    ThinkingConfig,
    TokenEstimate,
    TokenEstimateData,
    ToolCall,
    ToolDef,
    Usage,
    VideoUrl,
    VideoUrlPart,
)

__all__ = [
    "AVAILABLE_MODELS",
    "AssistantMessage",
    "AsyncKimiClient",
    "BalanceData",
    "BalanceInfo",
    "ChatCompletion",
    "ChatCompletionChunk",
    "ChatCompletionRequest",
    "Choice",
    "ChoiceDelta",
    "ContentPart",
    "FinishReason",
    "FunctionCall",
    "FunctionDef",
    "ImageUrl",
    "ImageUrlPart",
    "JsonSchemaSpec",
    "KimiAPIError",
    "KimiAuthenticationError",
    "KimiBadRequestError",
    "KimiClient",
    "KimiError",
    "KimiNotFoundError",
    "KimiPermissionError",
    "KimiRateLimitError",
    "KimiServerError",
    "Message",
    "Model",
    "ModelInfo",
    "ModelList",
    "ResponseFormat",
    "ResponseFormatType",
    "Role",
    "StreamChoice",
    "StreamOptions",
    "TextPart",
    "ThinkingConfig",
    "ThinkingMode",
    "TokenEstimate",
    "TokenEstimateData",
    "ToolCall",
    "ToolChoice",
    "ToolDef",
    "Usage",
    "VideoUrl",
    "VideoUrlPart",
    "main",
]


def main() -> None:
    print(f"kimi-agents-python — {len(AVAILABLE_MODELS)} models available:")
    for m in AVAILABLE_MODELS:
        print(f"  - {m.value}")
