from __future__ import annotations

from ._enums import (
    AVAILABLE_MODELS,
    BatchEndpoint,
    BatchStatus,
    FilePurpose,
    FinishReason,
    Model,
    ResponseFormatType,
    Role,
    ThinkingMode,
    ThinkingSupport,
    ToolChoice,
)
from .files import (
    BATCH_FORMATS,
    FILE_EXTRACT_FORMATS,
    IMAGE_FORMATS,
    MAX_FILE_BYTES,
    MAX_FILES,
    MAX_TOTAL_BYTES,
    VIDEO_FORMATS,
    file_extension,
    supported_formats,
    validate_file,
    validate_file_format,
    validate_file_size,
)
from .client import AsyncKimiClient, KimiClient
from .exceptions import (
    ContentFilterError,
    EngineOverloadedError,
    ExceededCurrentQuotaError,
    IncorrectAPIKeyError,
    InvalidAuthenticationError,
    InvalidRequestError,
    KimiAPIError,
    KimiAuthenticationError,
    KimiBadRequestError,
    KimiError,
    KimiNotFoundError,
    KimiPermissionError,
    KimiRateLimitError,
    KimiServerError,
    KimiToolLoopError,
    PermissionDeniedError,
    RateLimitReachedError,
    ResourceNotFoundError,
    ServerErrorResponse,
    UnexpectedOutputError,
)
from ._retry import DEFAULT_RETRY, NO_RETRY, RetryConfig
from ._stats import CacheStats
from .specs import MODEL_SPECS, ModelSpec, get_model_spec
from .tools import KimiTool, arun_tools, kimi_tool, run_tools
from .resources.files import FileContent
from .types import (
    AssistantMessage,
    BalanceData,
    BalanceInfo,
    Batch,
    BatchList,
    BatchRequestCounts,
    ChatCompletion,
    ChatCompletionChunk,
    ChatCompletionRequest,
    Choice,
    ChoiceDelta,
    ContentPart,
    FileDeleted,
    FileList,
    FileObject,
    FunctionCall,
    FunctionDef,
    ImageUrl,
    ImageUrlPart,
    JsonSchemaSpec,
    Message,
    ModelInfo,
    ModelList,
    PromptTokensDetails,
    ResponseFormat,
    StreamChoice,
    StreamOptions,
    TextPart,
    ThinkingConfig,
    TokenEstimate,
    TokenEstimateData,
    ToolCall,
    ToolDef,
    Usage,
    VideoUrl,
    VideoUrlPart,
)

__all__ = [
    "AVAILABLE_MODELS",
    "AssistantMessage",
    "AsyncKimiClient",
    "BATCH_FORMATS",
    "BalanceData",
    "BalanceInfo",
    "Batch",
    "BatchEndpoint",
    "BatchList",
    "BatchRequestCounts",
    "BatchStatus",
    "CacheStats",
    "ChatCompletion",
    "ChatCompletionChunk",
    "ChatCompletionRequest",
    "Choice",
    "ChoiceDelta",
    "ContentFilterError",
    "ContentPart",
    "DEFAULT_RETRY",
    "EngineOverloadedError",
    "ExceededCurrentQuotaError",
    "FILE_EXTRACT_FORMATS",
    "FileContent",
    "FileDeleted",
    "FileList",
    "FileObject",
    "FilePurpose",
    "FinishReason",
    "FunctionCall",
    "FunctionDef",
    "IMAGE_FORMATS",
    "ImageUrl",
    "ImageUrlPart",
    "IncorrectAPIKeyError",
    "InvalidAuthenticationError",
    "InvalidRequestError",
    "JsonSchemaSpec",
    "KimiAPIError",
    "KimiAuthenticationError",
    "KimiBadRequestError",
    "KimiClient",
    "KimiError",
    "KimiNotFoundError",
    "KimiPermissionError",
    "KimiRateLimitError",
    "KimiServerError",
    "KimiTool",
    "KimiToolLoopError",
    "MAX_FILE_BYTES",
    "MAX_FILES",
    "MAX_TOTAL_BYTES",
    "MODEL_SPECS",
    "Message",
    "Model",
    "ModelInfo",
    "ModelList",
    "ModelSpec",
    "NO_RETRY",
    "PermissionDeniedError",
    "PromptTokensDetails",
    "RateLimitReachedError",
    "ResourceNotFoundError",
    "ResponseFormat",
    "ResponseFormatType",
    "RetryConfig",
    "Role",
    "ServerErrorResponse",
    "StreamChoice",
    "StreamOptions",
    "TextPart",
    "ThinkingConfig",
    "ThinkingMode",
    "ThinkingSupport",
    "TokenEstimate",
    "TokenEstimateData",
    "ToolCall",
    "ToolChoice",
    "ToolDef",
    "UnexpectedOutputError",
    "Usage",
    "VIDEO_FORMATS",
    "VideoUrl",
    "VideoUrlPart",
    "arun_tools",
    "file_extension",
    "get_model_spec",
    "kimi_tool",
    "run_tools",
    "supported_formats",
    "validate_file",
    "validate_file_format",
    "validate_file_size",
]


def main() -> None:
    print(f"kimi-agents-python — {len(AVAILABLE_MODELS)} models available:")
    for m in AVAILABLE_MODELS:
        print(f"  - {m.value}")
